name: PitRemake
authors:
  - Kyro
  - Wiji
version: 1.0.0
main: dev.kyro.pitsim.PitSim
description: Remake of the Hypixel Pit
depend:
  - Citizens
  - Vault
  - PlaceholderAPI
commands:
  atest:
  enchant:
  fresh:
  non: