package dev.kyro.pitsim.misc;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PrivateInfo {
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
	//TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING

	public static final String PTERO_KEY = "VILPyBXQfdJUEJEd4HUUbvTKsyDfbVD8KjYTOk2DMmyPfxCD";
	public static final List<String> WHITELISTED_IPS = new ArrayList<>(Arrays.asList("/***REMOVED***", "/***REMOVED***"));
	public static final String ALERTS_WEBHOOK = "***REMOVED***";
}
