package net.pitsim.pitsim.misc;

public class Constant {
	public static final int JEWEL_KILLS = 42;

	public static final String PITSIM_CRATE =
			"rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph" +
					"dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk" +
					"U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG" +
					"dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9" +
					"PXQABHR5cGV0AARtZXRhdXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFj" +
					"a3QADVRSSVBXSVJFX0hPT0tzcQB+AABzcQB+AAN1cQB+AAYAAAAHcQB+AAh0AAltZXRhLXR5cGV0" +
					"AAxkaXNwbGF5LW5hbWV0AARsb3JldAAIZW5jaGFudHN0AAlJdGVtRmxhZ3N0AAhpbnRlcm5hbHVx" +
					"AH4ABgAAAAd0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AB/CpzbCp2xQaXTCp2XCp2xTaW0gwqc3" +
					"Q3JhdGUgS2V5c3IANmNvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlTGlzdCRTZXJp" +
					"YWxpemVkRm9ybQAAAAAAAAAAAgABWwAIZWxlbWVudHNxAH4ABHhwdXEAfgAGAAAAAnQAE8KnN1Vz" +
					"ZWQgdG8gb3BlbiB0aGV0ABnCpzdQaXRTaW0gQ3JhdGUgYXQgc3Bhd24uc3IAN2NvbS5nb29nbGUu" +
					"Y29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAHhx" +
					"AH4AA3VxAH4ABgAAAAF0AARMVUNLdXEAfgAGAAAAAXNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3" +
					"gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAAAABc3IAEWph" +
					"dmEudXRpbC5IYXNoU2V0ukSFlZa4tzQDAAB4cHcMAAAAED9AAAAAAAABdAANSElERV9FTkNIQU5U" +
					"U3h0AEBINHNJQUFBQUFBQUFBT05pWU9CZ0VIUXVTcXlxQkJJbHFjVzZZSXFCMVNteE9ET1pBUUQw" +
					"elRvU0h3QUFBQT09";
	public static final String TAINTED_CRATE =
			"rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph" +
					"dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk" +
					"U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG" +
					"dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9" +
					"PXQABHR5cGV0AARtZXRhdXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFj" +
					"a3QADVRSSVBXSVJFX0hPT0tzcQB+AABzcQB+AAN1cQB+AAYAAAAHcQB+AAh0AAltZXRhLXR5cGV0" +
					"AAxkaXNwbGF5LW5hbWV0AARsb3JldAAIZW5jaGFudHN0AAlJdGVtRmxhZ3N0AAhpbnRlcm5hbHVx" +
					"AH4ABgAAAAd0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0ABrCpzXCp2xUYWludGVkIMKnN0NyYXRl" +
					"IEtleXNyADZjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0YWJsZUxpc3QkU2VyaWFsaXpl" +
					"ZEZvcm0AAAAAAAAAAAIAAVsACGVsZW1lbnRzcQB+AAR4cHVxAH4ABgAAAAN0ABPCpzdVc2VkIHRv" +
					"IG9wZW4gdGhldAAZwqc1wqdsVGFpbnRlZCDCpzdDcmF0ZSBpbnQAFsKnN3RoZSDCpzVEYXJrem9u" +
					"ZcKnNy5zcgA3Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVCaU1hcCRTZXJpYWxp" +
					"emVkRm9ybQAAAAAAAAAAAgAAeHEAfgADdXEAfgAGAAAAAXQABExVQ0t1cQB+AAYAAAABc3IAEWph" +
					"dmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyV" +
					"HQuU4IsCAAB4cAAAAAFzcgARamF2YS51dGlsLkhhc2hTZXS6RIWVlri3NAMAAHhwdwwAAAAQP0AA" +
					"AAAAAAF0AA1ISURFX0VOQ0hBTlRTeHQAQEg0c0lBQUFBQUFBQUFPTmlZT0JnRUhRdVNxeXFCQkls" +
					"cWNXNllJcUJQU1F4TTY4a05ZVUJBUGkvME5JaEFBQUE=";
	public static final String PITSIM_BUNDLE =
			"rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph" +
					"dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk" +
					"U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG" +
					"dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9" +
					"PXQABHR5cGV0AARtZXRhdXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFj" +
					"a3QAC0VOREVSX0NIRVNUc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIdAAJbWV0YS10eXBldAAM" +
					"ZGlzcGxheS1uYW1ldAAEbG9yZXQACGludGVybmFsdXEAfgAGAAAABXQACEl0ZW1NZXRhdAAKVU5T" +
					"UEVDSUZJQ3QARcKnZcKnbCrCpzbCp2wqwqdlwqdsKiDCp2XCp2xQaXRTaW0gwqdlwqdsQnVuZGxl" +
					"IMKnZcKnbCrCpzbCp2wqwqdlwqdsKnNyADZjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LkltbXV0" +
					"YWJsZUxpc3QkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAVsACGVsZW1lbnRzcQB+AAR4cHVxAH4A" +
					"BgAAAB90ADbCpzdQdXJjaGFzZWQgYXQgwqc2c3RvcmUucGl0c2ltLm5ldCDCpzdieSDCpzZLeXJv" +
					"S3J5cHR0AAPCpzd0ABTCp2XCp2xOb3JtYWwgUmV3YXJkc3QADcKnZSogwqdmJDEwMGt0ABPCp2Uq" +
					"IMKnZk1vbmV5IFBvdWNodAAWwqdlKiDCp2YxeCBKZXdlbCBTd29yZHQAFsKnZSogwqdmMnggSmV3" +
					"ZWwgU3dvcmR0ABTCp2UqIMKnZjF4IEpld2VsIEJvd3QAFMKnZSogwqdmMnggSmV3ZWwgQm93dAAW" +
					"wqdlKiDCp2YxeCBKZXdlbCBQYW50c3QAFsKnZSogwqdmMnggSmV3ZWwgUGFudHN0ABXCp2UqIMKn" +
					"ZlByb3QgMSBIZWxtZXR0ABnCp2UqIMKnZlByb3QgMSBDaGVzdHBsYXRldAAXwqdlKiDCp2ZQcm90" +
					"IDEgTGVnZ2luZ3N0ABTCp2UqIMKnZlByb3QgMSBCb290c3QAGMKnZSogwqdmMXggRnVua3kgRmVh" +
					"dGhlcnQAGMKnZSogwqdmMXggQ2h1bmsgb2YgVmlsZXQAEcKnZSogwqdmMXggUmVub3dudAAcwqdl" +
					"KiDCp2YxeCBBbmNpZW50IEdlbSBTaGFyZHQAA8KnN3QAE8KnNsKnbEZpbmFsIFJld2FyZHN0ABnC" +
					"pzYqIMKnZkxhcmdlIE1vbmV5IFBvdWNodAASwqc2KiDCp2ZQcm90IDEgU2V0dAAYwqc2KiDCp2Y1" +
					"eCBGdW5reSBGZWF0aGVydAAYwqc2KiDCp2Y1eCBDaHVuayBvZiBWaWxldAAUwqc2KiDCp2ZKZXdl" +
					"bCBCdW5kbGV0ABrCpzYqIMKnZkxhcmdlIEpld2VsIEJ1bmRsZXQAEcKnNiogwqdmOHggUmVub3du" +
					"dAAcwqc2KiDCp2YzeCBBbmNpZW50IEdlbSBTaGFyZHQAA8KnN3QAJcKnY0NsZWFyIG91dCBpbnZl" +
					"bnRvcnkgYmVmb3JlIG9wZW5pbmd0AERINHNJQUFBQUFBQUFBT05pWU9CZ0VIRDBkZGJ6emM4cnlj" +
					"aXBkQzVLTEVsbFlDdklMQ25PekdVQUFHZUpzeFVmQUFBQQ==";
	public static final String SMALL_POUCH =
			"rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph" +
					"dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk" +
					"U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG" +
					"dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9" +
					"PXQABHR5cGV0AARtZXRhdXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFj" +
					"a3QAC0VOREVSX0NIRVNUc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIdAAJbWV0YS10eXBldAAM" +
					"ZGlzcGxheS1uYW1ldAAEbG9yZXQACGludGVybmFsdXEAfgAGAAAABXQACEl0ZW1NZXRhdAAKVU5T" +
					"UEVDSUZJQ3QALMKnZcKnbE5vcm1hbCBNb25leSBQb3VjaCDCp3LCpzcoUmlnaHQgQ2xpY2spc3IA" +
					"NmNvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlTGlzdCRTZXJpYWxpemVkRm9ybQAA" +
					"AAAAAAAAAgABWwAIZWxlbWVudHNxAH4ABHhwdXEAfgAGAAAAB3QAJcKnN1BsYWNlIHRoZSBNb25l" +
					"eSBQb3VjaCB0byByZWNlaXZlIGF0ABvCpzdNeXN0ZXJ5IHJld2FyZCBvZiBtb25leSF0AAB0ABjC" +
					"pzbCp2wqIMKnZVJld2FyZCAoZ29sZCl0ABPCpzgtIMKnZjAgLSAyMDAsMDAwdAAAdAAfwqc3wqdv" +
					"KCggUGxhY2UgZG93biB0byBvcGVuISApKXQAVEg0c0lBQUFBQUFBQUFPTmlZT0JnNEhUMGRkWUx5" +
					"QzlOem1CZ3k4c3Z5azNNNFdBUUFJbjU1dWVWWk9SVU9oY2xscVF5TURBQUFBV3RzWm90QUFBQQ==";
	public static final String LARGE_POUCH =
			"rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph" +
					"dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk" +
					"U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG" +
					"dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9" +
					"PXQABHR5cGV0AARtZXRhdXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFj" +
					"a3QAC0VOREVSX0NIRVNUc3EAfgAAc3EAfgADdXEAfgAGAAAABXEAfgAIdAAJbWV0YS10eXBldAAM" +
					"ZGlzcGxheS1uYW1ldAAEbG9yZXQACGludGVybmFsdXEAfgAGAAAABXQACEl0ZW1NZXRhdAAKVU5T" +
					"UEVDSUZJQ3QAK8KnNsKnbExhcmdlIE1vbmV5IFBvdWNoIMKncsKnNyhSaWdodCBDbGljaylzcgA2" +
					"Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVMaXN0JFNlcmlhbGl6ZWRGb3JtAAAA" +
					"AAAAAAACAAFbAAhlbGVtZW50c3EAfgAEeHB1cQB+AAYAAAAHdAAlwqc3UGxhY2UgdGhlIE1vbmV5" +
					"IFBvdWNoIHRvIHJlY2VpdmUgYXQAG8KnN015c3RlcnkgcmV3YXJkIG9mIG1vbmV5IXQAAHQAGMKn" +
					"NsKnbCogwqdlUmV3YXJkIChnb2xkKXQAG8KnOC0gwqdmMjAwLDAwMCAtIDIsMDAwLDAwMHQAAHQA" +
					"H8KnN8KnbygoIFBsYWNlIGRvd24gdG8gb3BlbiEgKSl0AFRINHNJQUFBQUFBQUFBT05pWU9CZzRI" +
					"VDBkZFlMeUM5TnptQmd6VWtzU2svbFlCQUFDZm5tNTVWazVGUTZGeVdXcERJd01BQUFXTVJYSGl3" +
					"QUFBQT0=";
}
