name: PitRemake
authors:
  - Kyro
  - Wiji
version: 1.0.0
main: dev.kyro.pitsim.PitSim
description: Remake of the Hypixel Pit
depend:
  - Citizens
  - PlaceholderAPI
  - NoteBlockAPI
  - ProtocolLib
  - PitRemakeDependencies
  - LiteBans
  - PremiumVanish
  - DeluxeChat
  - PluginQuery
softdepend: [GrimAC, PolarLoader]
commands:
  pitsim:
  ps:
  oof:
  atest:
  ktest:
  enchant:
  fresh:
  non:
  show:
  perks:
  jewel:
  market:
  enchants:
  setkills:
  togglestereo:
  donator:
  renown:
  bounty:
  spawn:
  changemap:
  reward:
  afk:
  pitreload:
  setvalue:
  check:
  shop:
  store:
  discord:
  disc:
  booster:
  boostergive:
  fps:
  resource:
  lightning:
  stat:
  play:
  pay:
  tutorial:
  shutdown:
  kit:
    aliases:
      - kits
  view:
  music:
  cutscene:
  migrate:
  pass:
  quests:
    aliases:
      - quest
  settings:
  setting:
  set:
  massmigrate:
  potions:
    aliases:
      - pot
      - potion
  eco:
  balance:
    aliases:
      - bal
  gamemode:
    aliases:
      - gm
      - gmc
      - gms
      - gma
      - gmsp
  nickname:
    aliases:
      - nick
  fly:
    aliases:
      - flight
  teleport:
    aliases:
      - tp
  teleporthere:
    aliases:
      - tphere
      - s
  broadcast:
    aliases:
      - bc
  trash:
    aliases:
      - disposal
  rename:
    aliases:
      - itemname
  ignore:
  cookie:
    aliases:
      - staffcookie
      - givecookie
  loadskin:
    aliases:
      - skin
  ineeddata:
  givemedata:
  massenchant:
  claim:
  beta: