package dev.kyro.pitsim.misc;

public class PrivateInfo {
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING













































    public static final String PTERO_KEY = "VILPyBXQfdJUEJEd4HUUbvTKsyDfbVD8KjYTOk2DMmyPfxCD";
}
