package dev.kyro.pitsim.misc;

public class PrivateInfo {
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING
    //TODO: DO NOT SCROLL DOWN WHILE SCREENSHARING













































    public static final String PTERO_KEY = "im4F1vVHTJKIjhRQcvJ8CAdOX3aCt99JmpukhFGbzQXI5BOQ";
}
